// Equipos por liga (temporada 2025-26)
// La búsqueda web complementará con datos actualizados de cada partido.
const LEAGUES = {
  "liga-betplay": {
    name: "Liga BetPlay Dimayor (Colombia)",
    country: "Colombia",
    teams: [
      "Águilas Doradas",
      "Alianza FC",
      "América de Cali",
      "Atlético Bucaramanga",
      "Atlético Nacional",
      "Boyacá Chicó",
      "Deportes Tolima",
      "Deportivo Cali",
      "Deportivo Pasto",
      "Deportivo Pereira",
      "Envigado FC",
      "Fortaleza CEIF",
      "Independiente Medellín",
      "Independiente Santa Fe",
      "Junior de Barranquilla",
      "La Equidad",
      "Llaneros FC",
      "Millonarios FC",
      "Once Caldas",
      "Unión Magdalena"
    ]
  },
  "premier-league": {
    name: "Premier League (Inglaterra)",
    country: "Inglaterra",
    teams: [
      "Arsenal",
      "Aston Villa",
      "Bournemouth",
      "Brentford",
      "Brighton & Hove Albion",
      "Burnley",
      "Chelsea",
      "Crystal Palace",
      "Everton",
      "Fulham",
      "Leeds United",
      "Liverpool",
      "Manchester City",
      "Manchester United",
      "Newcastle United",
      "Nottingham Forest",
      "Sunderland",
      "Tottenham Hotspur",
      "West Ham United",
      "Wolverhampton Wanderers"
    ]
  },
  "la-liga": {
    name: "LaLiga EA Sports (España)",
    country: "España",
    teams: [
      "Alavés",
      "Athletic Club",
      "Atlético de Madrid",
      "FC Barcelona",
      "Celta de Vigo",
      "Elche",
      "Espanyol",
      "Getafe",
      "Girona",
      "Levante",
      "Mallorca",
      "Osasuna",
      "Real Oviedo",
      "Rayo Vallecano",
      "Real Betis",
      "Real Madrid",
      "Real Sociedad",
      "Sevilla",
      "Valencia",
      "Villarreal"
    ]
  },
  "serie-a": {
    name: "Serie A (Italia)",
    country: "Italia",
    teams: [
      "Atalanta",
      "Bologna",
      "Cagliari",
      "Como",
      "Cremonese",
      "Fiorentina",
      "Genoa",
      "Hellas Verona",
      "Inter de Milán",
      "Juventus",
      "Lazio",
      "Lecce",
      "AC Milan",
      "Napoli",
      "Parma",
      "Pisa",
      "AS Roma",
      "Sassuolo",
      "Torino",
      "Udinese"
    ]
  },
  "bundesliga": {
    name: "Bundesliga (Alemania)",
    country: "Alemania",
    teams: [
      "FC Augsburg",
      "Bayer Leverkusen",
      "Bayern Múnich",
      "Borussia Dortmund",
      "Borussia Mönchengladbach",
      "Eintracht Frankfurt",
      "SC Freiburg",
      "Hamburger SV",
      "1. FC Heidenheim",
      "TSG Hoffenheim",
      "1. FC Köln",
      "RB Leipzig",
      "Mainz 05",
      "FC St. Pauli",
      "VfB Stuttgart",
      "Union Berlin",
      "Werder Bremen",
      "VfL Wolfsburg"
    ]
  },
  "ligue-1": {
    name: "Ligue 1 (Francia)",
    country: "Francia",
    teams: [
      "Angers SCO",
      "AJ Auxerre",
      "Stade Brestois",
      "Le Havre AC",
      "RC Lens",
      "Lille OSC",
      "FC Lorient",
      "Olympique de Lyon",
      "Olympique de Marsella",
      "AS Mónaco",
      "FC Metz",
      "FC Nantes",
      "OGC Nice",
      "Paris FC",
      "Paris Saint-Germain",
      "Stade Rennais",
      "RC Strasbourg",
      "Toulouse FC"
    ]
  },
  "champions-league": {
    name: "UEFA Champions League",
    country: "Europa",
    teams: [
      "Arsenal",
      "Atalanta",
      "Atlético de Madrid",
      "FC Barcelona",
      "Bayer Leverkusen",
      "Bayern Múnich",
      "Benfica",
      "Borussia Dortmund",
      "Chelsea",
      "Club Brugge",
      "Eintracht Frankfurt",
      "Galatasaray",
      "Inter de Milán",
      "Juventus",
      "Liverpool",
      "Manchester City",
      "AC Milan",
      "AS Mónaco",
      "Napoli",
      "Olympiacos",
      "Olympique de Marsella",
      "Paris Saint-Germain",
      "PSV Eindhoven",
      "Real Madrid",
      "Sporting CP",
      "Tottenham Hotspur",
      "Villarreal"
    ]
  },
  "europa-league": {
    name: "UEFA Europa League",
    country: "Europa",
    teams: [
      "Aston Villa",
      "Real Betis",
      "Bologna",
      "Celta de Vigo",
      "Celtic",
      "Dinamo Zagreb",
      "FC Basel",
      "Feyenoord",
      "Fenerbahçe",
      "Ferencváros",
      "Lille OSC",
      "Lyon",
      "Maccabi Tel Aviv",
      "Midtjylland",
      "Nottingham Forest",
      "Panathinaikos",
      "Porto",
      "Rangers",
      "Red Bull Salzburg",
      "AS Roma",
      "Stuttgart",
      "Viktoria Plzeň",
      "Young Boys"
    ]
  },
  "copa-libertadores": {
    name: "Copa Libertadores (CONMEBOL)",
    country: "Sudamérica",
    teams: [
      "Alianza Lima",
      "América de Cali",
      "Athletico Paranaense",
      "Atlético Mineiro",
      "Atlético Nacional",
      "Barcelona SC",
      "Boca Juniors",
      "Bolívar",
      "Botafogo",
      "Cerro Porteño",
      "Colo-Colo",
      "Corinthians",
      "Estudiantes de La Plata",
      "Flamengo",
      "Fluminense",
      "Independiente del Valle",
      "Internacional",
      "Junior de Barranquilla",
      "LDU Quito",
      "Libertad",
      "Millonarios FC",
      "Nacional (Uruguay)",
      "Olimpia",
      "Palmeiras",
      "Peñarol",
      "Racing Club",
      "River Plate",
      "Santos",
      "São Paulo",
      "Sporting Cristal",
      "Universidad Católica",
      "Universitario"
    ]
  }
};
